In [2]:
#Thomas Conibear - One-Rule Machine Learning Homework

#From notes we know that it is easier for a computer to find a rule if all values are one or zero
#From notes we have the simple code to achieve this

from sklearn.datasets import load_iris
import numpy as np

dataset = load_iris() #Data from sklearn library
X = dataset.data
Y = dataset.target

X_d = np.array( X>X.mean(), dtype='int') #Converts to ones and zeroes using mean values

In [3]:
#From notes to get a table of ones and zeroes
from collections import OrderedDict
import pandas as pd

Iris_data_d = OrderedDict({'Sepal Length ': X_d[:,0],
             'Sepal Width': X_d[:,1],
             'Petal Length': X_d[:,2],
             'Petal Width': X_d[:,3],
             'Label': Y})

table = pd.DataFrame(Iris_data_d)
table

     Sepal Length   Sepal Width  Petal Length  Petal Width  Label
0                1            1             0            0      0
1                1            0             0            0      0
2                1            0             0            0      0
3                1            0             0            0      0
4                1            1             0            0      0
5                1            1             0            0      0
6                1            0             0            0      0
7                1            0             0            0      0
8                1            0             0            0      0
9                1            0             0            0      0
10               1            1             0            0      0
11               1            0             0            0      0
12               1            0             0            0      0
13               1            0             0            0      0
14               1            1             0            0      0
15               1            1             0            0      0
16               1            1             0            0      0
17               1            1             0            0      0
18               1            1             0            0      0
19               1            1             0            0      0
20               1            0             0            0      0
21               1            1             0            0      0
22               1            1             0            0      0
23               1            0             0            0      0
24               1            0             0            0      0
25               1            0             0            0      0
26               1            0             0            0      0
27               1            1             0            0      0
28               1            0             0            0      0
29               1            0             0            0      0
..             ...          ...           ...          ...    ...
120              1            0             1            0      2
121              1            0             1            0      2
122              1            0             1            0      2
123              1            0             1            0      2
124              1            0             1            0      2
125              1            0             1            0      2
126              1            0             1            0      2
127              1            0             1            0      2
128              1            0             1            0      2
129              1            0             1            0      2
130              1            0             1            0      2
131              1            1             1            0      2
132              1            0             1            0      2
133              1            0             1            0      2
134              1            0             1            0      2
135              1            0             1            0      2
136              1            0             1            0      2
137              1            0             1            0      2
138              1            0             1            0      2
139              1            0             1            0      2
140              1            0             1            0      2
141              1            0             1            0      2
142              1            0             1            0      2
143              1            0             1            0      2
144              1            0             1            0      2
145              1            0             1            0      2
146              1            0             1            0      2
147              1            0             1            0      2
148              1            0             1            0      2
149              1            0             1            0      2

[150 rows x 5 columns]

In [4]:
#Kept getting error that index 4 is out of bounds for axis 1 with size 4 with the data as it is
#So I searched online and found that all the arrays needed to be remade and reshaped


# Assigning value of one to values above the mean and zero to those below

X_new_0 = np.array( X[:,0] > X[:,0].mean(), dtype = 'int')
X_new_1 = np.array( X[:,1] > X[:,1].mean(), dtype = 'int')
X_new_2 = np.array( X[:,2] > X[:,2].mean(), dtype = 'int')
X_new_3 = np.array( X[:,3] > X[:,3].mean(), dtype = 'int')

#Reshaping the arrays

X_final0 = X_new_0.reshape(150,1)
X_final1 = X_new_1.reshape(150,1)
X_final2 = X_new_2.reshape(150,1)
X_final3 = X_new_3.reshape(150,1)
Y_d = Y.reshape(150,1)

In [5]:
Iris_data_2 = OrderedDict({'Sepal Length ': X_final0[:,0],
             'Sepal Width': X_final1[:,0],
             'Petal Length': X_final2[:,0],
             'Petal Width': X_final3[:,0],
             'Label': Y})

table2 = pd.DataFrame(Iris_data_2)
table2

     Sepal Length   Sepal Width  Petal Length  Petal Width  Label
0                0            1             0            0      0
1                0            0             0            0      0
2                0            1             0            0      0
3                0            1             0            0      0
4                0            1             0            0      0
5                0            1             0            0      0
6                0            1             0            0      0
7                0            1             0            0      0
8                0            0             0            0      0
9                0            1             0            0      0
10               0            1             0            0      0
11               0            1             0            0      0
12               0            0             0            0      0
13               0            0             0            0      0
14               0            1             0            0      0
15               0            1             0            0      0
16               0            1             0            0      0
17               0            1             0            0      0
18               0            1             0            0      0
19               0            1             0            0      0
20               0            1             0            0      0
21               0            1             0            0      0
22               0            1             0            0      0
23               0            1             0            0      0
24               0            1             0            0      0
25               0            0             0            0      0
26               0            1             0            0      0
27               0            1             0            0      0
28               0            1             0            0      0
29               0            1             0            0      0
..             ...          ...           ...          ...    ...
120              1            1             1            1      2
121              0            0             1            1      2
122              1            0             1            1      2
123              1            0             1            1      2
124              1            1             1            1      2
125              1            1             1            1      2
126              1            0             1            1      2
127              1            0             1            1      2
128              1            0             1            1      2
129              1            0             1            1      2
130              1            0             1            1      2
131              1            1             1            1      2
132              1            0             1            1      2
133              1            0             1            1      2
134              1            0             1            1      2
135              1            0             1            1      2
136              1            1             1            1      2
137              1            1             1            1      2
138              1            0             1            1      2
139              1            1             1            1      2
140              1            1             1            1      2
141              1            1             1            1      2
142              0            0             1            1      2
143              1            1             1            1      2
144              1            1             1            1      2
145              1            0             1            1      2
146              1            0             1            1      2
147              1            0             1            1      2
148              1            1             1            1      2
149              1            0             1            1      2

[150 rows x 5 columns]

In [75]:
#Defining new array to merge all of our arrays into one to more easily operate on
Z_d = np.hstack([X_final0,X_final1,X_final2,X_final3,Y_d])

#Better way to show what we are looking at with results
a = ['Sepal Length:','Sepal Width','Petal Length:','Petal Width:']
b = ['Setosa','Versicolor','Virginica']
Percentages = []
for i in range(4):
    for j in range(3):
        selection = np.logical_and(Z_d[:,i]>.9,Z_d[:,4] == j)
        Percentages.append(( a[i], b[j],'Selected Values:', len(Z_d[selection]),'Associated Percentage:', round((len(Z_d[selection])/len(Z_d[:,i]))*100,2)))

In [77]:
# Percentages
# This better presents the data as it would normally just list out the data in a really ugly way if I called the array
for tuple in Percentages:
    print(tuple[0], tuple[1])
    print(tuple[2], tuple[3])
    print(tuple[4], tuple[5], "\n")

Sepal Length: Setosa
Selected Values: 0
Associated Percentage: 0.0

Sepal Length: Versicolor
Selected Values: 26
Associated Percentage: 17.33

Sepal Length: Virginica
Selected Values: 44
Associated Percentage: 29.33

Sepal Width Setosa
Selected Values: 42
Associated Percentage: 28.0

Sepal Width Versicolor
Selected Values: 8
Associated Percentage: 5.33

Sepal Width Virginica
Selected Values: 17
Associated Percentage: 11.33

Petal Length: Setosa
Selected Values: 0
Associated Percentage: 0.0

Petal Length: Versicolor
Selected Values: 43
Associated Percentage: 28.67

Petal Length: Virginica
Selected Values: 50
Associated Percentage: 33.33

Petal Width: Setosa
Selected Values: 0
Associated Percentage: 0.0

Petal Width: Versicolor
Selected Values: 40
Associated Percentage: 26.67

Petal Width: Virginica
Selected Values: 50
Associated Percentage: 33.33